name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'proxy.worker.js'
      - 'wrangler.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm && pnpm --version

      - name: Install wrangler
        run: pnpm add -g wrangler@3

      - name: Deploy to Cloudflare Workers
        run: npx wrangler@3 deploy --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
