name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'proxy.worker.js'
      - 'wrangler.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --name 5572tv-proxy --route "www.5572.net/api/proxy/*"
